- name: Creating Security Group
  local_action:
    module: ec2_group
    name: "{{ security_group }}"
    description: Security Group EC2
    region: "{{ region }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
      rule_desc: SSH
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Creating EC2 machine
  local_action: ec2
    group={{ security_group }}
    instance_type={{ instance_type }}
    image={{ image }}
    wait=true
    region={{ region }}
    keypair={{ keypair }}
    count={{ count }}
  register: ec2

- name: Allocating elastic IP to instance
  ec2_eip: 
    region: "{{ region }}"
    in_vpc: yes
    reuse_existing_ip_allowed: no
    state: present
    device_id: "{{ item.id }}"
  with_items: "{{ ec2.instances }}"  
  register: eip
- debug: var=eip  

- name: Add instance to the inventory temp
  add_host: name={{ item.public_ip }} groups=my-machines-new
  with_items: "{{ eip.results }}"  

######################
# With EIP
######################
- name: Add public IP from the new instance to the hosts file
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[ec2ips]" line={{ item.public_ip }}
  with_items: "{{ eip.results }}"

- name: Waiting SSH
  local_action: wait_for
    host={{ item.public_ip }}
    port=22
    state=started
  with_items: "{{ eip.results }}"

######################
# Without EIP
######################
#- name: Add public IP from the new instance to the hosts file
#  local_action: lineinfile
#    dest="./hosts"
#    regexp={{ item.public_ip }}
#    insertafter="[ec2ips]" line={{ item.public_ip }}
#  with_items: "{{ ec2.instances }}"
#
#- name: Waiting SSH
#  local_action: wait_for
#    host={{ item.public_ip }}
#    port=22
#    state=started
#  with_items: "{{ ec2.instances }}"

- name: Add tag name to the instance
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: ansible-{{ item.ami_launch_index|int + 1 }}